package com.unkwn2.yandexhud.util

import android.content.Context
import android.content.SharedPreferences
import android.provider.Settings
import android.util.Base64
import java.math.BigInteger
import java.security.KeyFactory
import java.security.Signature
import java.security.spec.RSAPublicKeySpec
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object LicenseManager {
    private const val PREFS_NAME = "yandexhud_license"
    private const val KEY_LICENSE = "license_data"
    private const val KEY_LAST_DATE = "last_valid_date"
    private const val DATE_FORMAT = "yyyy-MM-dd"

    // --- RSA-2048 Public Key (Modulus + Exponent) ---
    // Generated by LicenseGenerator --genkey.
    // REPLACE with your own key for production builds.
    private val PUB_KEY_MODULUS = run {
        val raw = Base64.decode("tl3kc8O2aJ/ccGz9680lY8IOA1KlumFI13NEI5bTRNVJ4H1iewUOOiwNglBfHuGvfZiPffcNwrpK0PUrbghGZYVLuCveRfqzsu1U5QQvyCP+5LxRaXkXo8u4JzLyXmHHpvbezD3c94+C6UxNYIiYC0mET+RVjhmsnMnThKC8zOr35BrofcTcV37BEpX2p21yKGaa9qNMeM3ay05UqIynm/dr5iH+0ea1z76CHFqW1cFc3NgvNqY0cRLFH4VcA/vOqP8xXm3KxB8zjtHwvmsHI/pyM6CMWdJZtTEDlkQgtTCFjv5yDr0t88BtUrKjV0JDn5Pf4o4fh3JlSR2JoUSvgQ==", Base64.DEFAULT)
        BigInteger(1, raw)
    }
    private val PUB_KEY_EXPONENT = BigInteger.valueOf(65537L)

    private val keyFactory = KeyFactory.getInstance("RSA")
    private val publicKey = keyFactory.generatePublic(
        RSAPublicKeySpec(PUB_KEY_MODULUS, PUB_KEY_EXPONENT)
    )

    data class LicenseData(
        val deviceId: String,
        val licenseType: String,
        val expiry: String,
        val customer: String
    )

    fun getDeviceId(ctx: Context): String {
        val androidId = Settings.Secure.getString(ctx.contentResolver, Settings.Secure.ANDROID_ID) ?: ""
        return androidId.ifEmpty {
            // fallback: use installation fingerprint
            val sha1 = java.security.MessageDigest.getInstance("SHA-1")
            val sig = sha1.digest(ctx.packageManager.getPackageInfo(ctx.packageName, 0).signingInfo.apkContentsSigners[0].toByteArray())
            Base64.encodeToString(sig, Base64.NO_WRAP or Base64.NO_PADDING)
        }
    }

    fun verifyLicense(licenseStr: String, deviceId: String): LicenseData? {
        // Format: BASE64(JSON).BASE64(SIGNATURE)
        val dot = licenseStr.lastIndexOf('.')
        if (dot <= 0) return null

        val jsonB64 = licenseStr.substring(0, dot)
        val sigB64 = licenseStr.substring(dot + 1)

        if (jsonB64.isBlank() || sigB64.isBlank()) return null

        val jsonBytes: ByteArray
        val sigBytes: ByteArray
        try {
            jsonBytes = Base64.decode(jsonB64, Base64.DEFAULT)
            sigBytes = Base64.decode(sigB64, Base64.DEFAULT)
        } catch (_: Exception) { return null }

        // Verify RSA signature
        try {
            val sig = Signature.getInstance("SHA256withRSA")
            sig.initVerify(publicKey)
            sig.update(jsonBytes)
            if (!sig.verify(sigBytes)) return null
        } catch (_: Exception) { return null }

        // Parse JSON
        val json = try { org.json.JSONObject(String(jsonBytes, Charsets.UTF_8)) }
        catch (_: Exception) { return null }

        val licenseDeviceId = json.optString("deviceId", "")
        val licenseType = json.optString("licenseType", "")
        val expiry = json.optString("exp", "")
        val customer = json.optString("customer", "")

        // Verify device ID
        if (licenseDeviceId != deviceId) return null

        // Verify expiry
        if (expiry.isNotEmpty()) {
            try {
                val fmt = SimpleDateFormat(DATE_FORMAT, Locale.US)
                fmt.isLenient = false
                val expDate = fmt.parse(expiry) ?: return null
                if (expDate.before(Date())) return null
            } catch (_: Exception) { return null }
        }

        return LicenseData(licenseDeviceId, licenseType, expiry, customer)
    }

    fun isLicenseValid(ctx: Context): Boolean {
        val prefs = getPrefs(ctx)
        val stored = prefs.getString(KEY_LICENSE, null) ?: return false
        val deviceId = getDeviceId(ctx)

        val license = verifyLicense(stored, deviceId) ?: return false
        val lastDate = prefs.getLong(KEY_LAST_DATE, 0L)

        // Date rollback protection
        val today = System.currentTimeMillis()
        if (lastDate > 0 && today < lastDate - 86400000L) {
            // System clock was rolled back by more than 1 day
            return false
        }

        // Save current date
        prefs.edit().putLong(KEY_LAST_DATE, today).apply()

        return true
    }

    fun saveLicense(ctx: Context, licenseStr: String): Boolean {
        val deviceId = getDeviceId(ctx)
        val license = verifyLicense(licenseStr, deviceId) ?: return false

        getPrefs(ctx).edit()
            .putString(KEY_LICENSE, licenseStr)
            .putLong(KEY_LAST_DATE, System.currentTimeMillis())
            .apply()
        return true
    }

    fun clearLicense(ctx: Context) {
        getPrefs(ctx).edit().clear().apply()
    }

    private fun getPrefs(ctx: Context): SharedPreferences =
        ctx.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
}