/**
 * LicenseGenerator — CLI tool for generating RSA-2048 signed licenses.
 *
 * Usage:
 *   1. Generate key pair:
 *      kotlin LicenseGenerator.kt --genkey
 *
 *   2. Sign a license:
 *      kotlin LicenseGenerator.kt --sign <deviceId> <expiry> <customer>
 *
 * Output:
 *   - BASE64(JSON).BASE64(SIGNATURE) — paste into the app
 *
 * Requirements:
 *   - Kotlin compiler (kotlinc) or run as script with `kotlin`
 *   - Private key embedded or generated
 */

import java.io.ByteArrayOutputStream
import java.io.ObjectOutputStream
import java.math.BigInteger
import java.security.*
import java.security.spec.PKCS8EncodedKeySpec
import java.security.spec.RSAPrivateCrtKeySpec
import java.security.spec.RSAPublicKeySpec
import java.util.*

// ============================================================
// EDIT THIS: paste your Base64-encoded private key parameters
// (generated by --genkey mode)
// ============================================================
private const val PRIV_MODULUS_B64 = "tl3kc8O2aJ/ccGz9680lY8IOA1KlumFI13NEI5bTRNVJ4H1iewUOOiwNglBfHuGvfZiPffcNwrpK0PUrbghGZYVLuCveRfqzsu1U5QQvyCP+5LxRaXkXo8u4JzLyXmHHpvbezD3c94+C6UxNYIiYC0mET+RVjhmsnMnThKC8zOr35BrofcTcV37BEpX2p21yKGaa9qNMeM3ay05UqIynm/dr5iH+0ea1z76CHFqW1cFc3NgvNqY0cRLFH4VcA/vOqP8xXm3KxB8zjtHwvmsHI/pyM6CMWdJZtTEDlkQgtTCFjv5yDr0t88BtUrKjV0JDn5Pf4o4fh3JlSR2JoUSvgQ=="
private const val PRIV_EXPONENT_B64 = "AQAB"
private const val PRIV_D_B64 = "r3DUfqohqbVhFKdGALty5O2jHX89AHjm4p55RuOqi+XFFLqLK15JuZz3wg4f9E2ZznIeWUh7bIJbx3qVNV2wm6oIlj1dsGTmy5OWwFuuvBQk+1hP2fAs1d7+YneYw0O+FtoYrNQ259KgVmCZb+z4mKM5LsKzq+j3Lj7bxhP8jgU8ORRr0WqdOJYpKycPP5t/YZxMYye6k1Z2LtKCXjHf2m4pV3ILaN15t9tMFvZcZwHLsQx4gqKfPOafIvrcxkFLfit25lvf9NaDZY63D9WCTpUZ4V7JJzzwY68mZP7qJIIMWd+L++5nv3zx5tz7kMRTth4/dbtlzYNrfs0KPbOvoQ=="
private const val PRIV_P_B64 = "8B1JOXSqZW4TZ/VTmaQK/z6iU+bmZLb4WnWwqAvD3eR9rDYEUNtKR8CFRH9fFwGTlAUvbzfRmFxQJSkX8grU5mJeHjQiCc/fnni2g8fLr/Ggdz2+LdHqLMaofbLCK0wenmDetfEhUj7CRTcRWHQXt6JQaOBNRNka1ztP4GDDkWs="
private const val PRIV_Q_B64 = "wm6PRKlyXpnzo/NB7mnTTLEy03S+cPQlb658svGc+d8tl8ac7+RzCS1x8LdhnOElnswxI/t41kr7vxMzCuxDlTfzdtD0tKPb01cQn1nGaMDj3pve4iDYdIWt72jlANzz8zcrwyZ/4BF8YXUw02xgKIxgYn7phmp6y4kbfJOSgcM="
private const val PRIV_DP_B64 = "UF59E+4o2qptdG54/QQbajPcwZiXpT5ZAm5CIv1NIghIyEuMRkQgKMQX10WK3nh4nSLfLarRTN4ZNVb73NgjSrnCJvnsKryZbMGa1aEaXFnUDBVugoewiiw0WV5r/3ILDZf+84cyUAURoXk9JQ42ohCCOZhaRKEmisQfiErbKuE="
private const val PRIV_DQ_B64 = "hBgzE9X/UtBLXA7Ps1eIa+lTe6AsJndo27hzFeva11ROGHiidMUDdq++YmlkUv4P3hQiKq0VyplE8ersWbZsr/tEWGvcZMGSfsH/FBQdHVw3NC03vu/Lv1Z29lmQhAaZYpsQC1SjuiqHE3tYAbv2lHXSofhRVbYP2So8V2W3Ops="
private const val PRIV_INVQ_B64 = "yFfpvve7n0BhKpymi8b6ydyCWXVk45wiJwe0/JDfSwNqNhWsF7+qPNQdrVn12RMklpSK9T7LKq+nrK1I2Lno0ZfpVCZ7bqWY+3F0k4lVXu1AoIj6HsxQKh7hUnyiLCYK/fLEiHqwWgWI1d75mpDhxKM8lHSejQbIcVmN3ZjM3gY="

fun main(args: Array<String>) {
    if (args.isEmpty()) {
        printUsage()
        return
    }

    when (args[0]) {
        "--genkey" -> generateKeyPair()
        "--sign" -> {
            if (args.size < 4) {
                println("Usage: --sign <deviceId> <expiry(yyyy-MM-dd)> <customer>")
                return
            }
            signLicense(args[1], args[2], args[3])
        }
        "--pubkey" -> printPublicKey()
        else -> printUsage()
    }
}

fun printUsage() {
    println("LicenseGenerator v1.0")
    println("Usage:")
    println("  --genkey                              Generate a new RSA-2048 key pair")
    println("  --sign <deviceId> <expiry> <customer> Sign a license")
    println("  --pubkey                              Print public key (for embedding)")
    println()
    println("Examples:")
    println("  LicenseGenerator --genkey")
    println("  LicenseGenerator --sign abc123 2027-12-31 Client")
}

fun generateKeyPair() {
    println("Generating RSA-2048 key pair...")
    val kpg = KeyPairGenerator.getInstance("RSA")
    kpg.initialize(2048, SecureRandom())
    val kp = kpg.generateKeyPair()

    val factory = KeyFactory.getInstance("RSA")
    val privKey = factory.getKeySpec(kp.private, RSAPrivateCrtKeySpec::class.java)
    val pubKey = factory.getKeySpec(kp.public, RSAPublicKeySpec::class.java)

    val b64 = Base64.getEncoder()

    println()
    println("=== PRIVATE KEY (keep secret!) ===")
    println("// --- Private Key Parameters for LicenseGenerator ---")
    println("private const val PRIV_MODULUS_B64 = \"${b64.encodeToString(privKey.modulus.toByteArray())}\"")
    println("private const val PRIV_EXPONENT_B64 = \"${b64.encodeToString(pubKey.publicExponent.toByteArray())}\"")
    println("private const val PRIV_D_B64 = \"${b64.encodeToString(privKey.privateExponent.toByteArray())}\"")
    println("private const val PRIV_P_B64 = \"${b64.encodeToString(privKey.primeP.toByteArray())}\"")
    println("private const val PRIV_Q_B64 = \"${b64.encodeToString(privKey.primeQ.toByteArray())}\"")
    println("private const val PRIV_DP_B64 = \"${b64.encodeToString(privKey.primeExponentP.toByteArray())}\"")
    println("private const val PRIV_DQ_B64 = \"${b64.encodeToString(privKey.primeExponentQ.toByteArray())}\"")
    println("private const val PRIV_INVQ_B64 = \"${b64.encodeToString(privKey.crtCoefficient.toByteArray())}\"")

    println()
    println("=== PUBLIC KEY (embed in LicenseManager.kt) ===")
    println("// --- Public Key for LicenseManager ---")
    println("private const val PUB_KEY_MODULUS_B64 = \"${b64.encodeToString(pubKey.modulus.toByteArray())}\"")
    println("private const val PUB_KEY_EXPONENT_B64 = \"${b64.encodeToString(pubKey.publicExponent.toByteArray())}\"")

    println()
    println("Saved private key to license_private.pem")
    java.nio.file.Files.write(java.nio.file.Paths.get("license_private.pem"), kp.private.encoded)
    println("Saved public key to license_public.der")
    java.nio.file.Files.write(java.nio.file.Paths.get("license_public.der"), kp.public.encoded)
}

fun signLicense(deviceId: String, expiry: String, customer: String) {
    // Build private key from embedded parameters
    val b64 = Base64.getDecoder()
    val modulus = BigInteger(1, b64.decode(PRIV_MODULUS_B64))
    val exponent = BigInteger(1, b64.decode(PRIV_EXPONENT_B64))
    val d = BigInteger(1, b64.decode(PRIV_D_B64))
    val p = BigInteger(1, b64.decode(PRIV_P_B64))
    val q = BigInteger(1, b64.decode(PRIV_Q_B64))
    val dp = BigInteger(1, b64.decode(PRIV_DP_B64))
    val dq = BigInteger(1, b64.decode(PRIV_DQ_B64))
    val invQ = BigInteger(1, b64.decode(PRIV_INVQ_B64))

    val spec = RSAPrivateCrtKeySpec(modulus, exponent, d, p, q, dp, dq, invQ)
    val factory = KeyFactory.getInstance("RSA")
    val privateKey = factory.generatePrivate(spec)

    // Build JSON
    val json = """{"deviceId":"$deviceId","licenseType":"PRO","exp":"$expiry","customer":"$customer"}"""
    val jsonBytes = json.toByteArray(Charsets.UTF_8)

    // Sign
    val sig = Signature.getInstance("SHA256withRSA")
    sig.initSign(privateKey)
    sig.update(jsonBytes)
    val signatureBytes = sig.sign()

    // Encode
    val jsonB64 = Base64.getEncoder().encodeToString(jsonBytes)
    val sigB64 = Base64.getEncoder().encodeToString(signatureBytes)

    val license = "$jsonB64.$sigB64"

    println()
    println("=== LICENSE ===")
    println(license)
    println()
    println("=== JSON DECODED ===")
    println(json)
    println()
    println("Paste the license line into the app.")
}

fun printPublicKey() {
    val b64 = Base64.getEncoder()
    val decoder = Base64.getDecoder()
    val modulus = BigInteger(1, decoder.decode(PRIV_MODULUS_B64))
    val exponent = BigInteger(1, decoder.decode(PRIV_EXPONENT_B64))
    println()
    println("=== PUBLIC KEY (for embedding in LicenseManager.kt) ===")
    println()
    println("private val PUB_KEY_MODULUS = BigInteger(1, Base64.decode(")
    println("    \"${b64.encodeToString(modulus.toByteArray())}\",")
    println("    Base64.DEFAULT")
    println("))")
    println("private val PUB_KEY_EXPONENT = BigInteger(1, Base64.decode(")
    println("    \"${b64.encodeToString(exponent.toByteArray())}\",")
    println("    Base64.DEFAULT")
    println("))")
}
